### PR TITLE
Add snapshot-based testing

### PR DESCRIPTION
**Pull request by RReverser**
This adds snapshot-based testing based on insta and (almost undocumented) virtual camera driver in libgphoto2, which should make it a lot easier to refactor code without having to verify that it still works with real cameras. These tests don't cover all the methods yet, but they already helped find couple of bugs like #22, #27, as well as few small issues in libgphoto2 itself.

This took a long time and surprisingly lots of effort to integrate (partially because of mentioned upstream issues with the driver, partially because of lack of documentation, and partially because of cross-platform shenanigans), but, on the bright side, it should make things a bit easier from now on, both for gphoto2-rs itself as well as for downstream users, who can now add `gphoto2-test` as a dependency and write their own tests based on it too.

As part of this PR I also renamed a few methods - if you prefer for me to split those out into separate PRs, I can do that too.

### CODE REVIEW

**Comment by maxicarlos08** [comment]
LOL I was just about to say that you should mark `build.sh` as executable :rofl:

**Comment by maxicarlos08** [comment]
This is awesome :+1:

Do these tests also run on Windows and MacOS? If yes I will setup a Github Actions matrix to also run them on those systems so I don't accidentally push any linux only changes again :)

**Comment by RReverser** [comment]
> Do these tests also run on Windows and MacOS? If yes I will setup a Github Actions matrix to also run them on those systems so I don't accidentally push any linux only changes again :)

I actually had a branch for that too 😅 I can rebase and push, but, fair warning, building on Windows seems much slower (due to installation of MSYS, as well as, after this PR, building the vusb port too). I guess doesn't matter too much?

**Comment by RReverser** [comment]
But yeah they work on Linux and Windows at least. Give me a bit of time to get this PR working on CI too first...

**Comment by maxicarlos08** [comment]
> I can rebase and push [...] I guess doesn't matter too much?

:+1: please do

**Comment by maxicarlos08** [comment]
What is wrong with libgphoto2 ???? On Github actions 5 tests failed, on my machine 1 failed and in my Ubuntu VM libgphoto2 doesn't even want to compile (`gphoto2-port-log.h:24:10: fatal error: 'stdarg.h' file not found`)

**Comment by RReverser** [comment]
> Give me a bit of time to get this PR working on CI too first...

Please wait a bit :P I'm trying to fix that. I think (hope) it just needs pinned revision, trying that now.

**Comment by RReverser** [comment]
Although probably something else. Weird that it worked consistently for me locally. Maybe there's more dynamic stuff at play that needs to be patched out aside from `mtime` (e.g. folder permissions for virtual filesystem differ between my machine and others?). Looking into it...

**Comment by RReverser** [comment]
> in my Ubuntu VM libgphoto2 doesn't even want to compile (`gphoto2-port-log.h:24:10: fatal error: 'stdarg.h' file not found`)

That one is really weird though. Idk why your compiler wouldn't find stdarg.h :/

**Comment by RReverser** [comment]
This doesn't make any sense. My next thought that maybe CI had a different version of libgphoto2-dev package, but no, CI and me locally both have `2.5.25-0ubuntu0.1`. Weeeeird.

**Comment by RReverser** [comment]
Oh. No, right, locally I did `make install` in libgphoto2 directory which probably changed everything. Ugh. I'll revert that and update snapshots.

**Comment by maxicarlos08** [comment]
`2.5.30-1`

**Comment by RReverser** [comment]
If this continues, perhaps the most reliable option will be to modify gphoto2-test to build entire libgphoto2 instead of just the vusb driver, and then hook the locally built version up to gphoto2-rs (that requires changing `build.rs` so that it doesn't look in pkg-config anymore).

**Comment by RReverser** [comment]
> `2.5.30-1`

Ah that explains the discrepancy with the CI then; CI has 2.5.25.

**Comment by maxicarlos08** [comment]
> If this continues, perhaps the most reliable option will be to modify gphoto2-test to build entire libgphoto2 instead of just the vusb driver, and then hook the locally built version up to gphoto2-rs (that requires changing `build.rs` so that it doesn't look in pkg-config anymore).

I guess thats the only way to go around these issues

**Comment by RReverser** [comment]
Oh well, I finally got it to fail locally, but yeah, looks like building entire libgphoto2 is the only way. I have to run now - if you want, feel free to give it a go, if not, I'll do that a bit later then.

**Comment by maxicarlos08** [comment]
> if you want, feel free to give it a go

My family is waiting for me to do my homework :P, if you haven't already I will see what I can do tonight

**Comment by RReverser** [comment]
Fair enough :) It's pretty cool that you're working on something like this already being in school and all btw. Enjoy!

**Comment by RReverser** [comment]
Ok done.

**Comment by maxicarlos08** [comment]
Ok, so the CI runs now, but I'm still getting the **exact** same diff as previously. I tried re-cloning the repository, reinstalling libgphoto2 (shouldn't make a difference anyway), idk what else to do.

**Review by maxicarlos08 — APPROVED** [review]
I think I will just merge this now and ignore the constant bit-flips happening on my machine if thats OK for you

**Comment by RReverser** [comment]
> but I'm still getting the **exact** same diff as previously

Even with custom-built libgphoto2? Wtf :/

**Comment by RReverser** [comment]
Can you run `cargo test --feature alt_logs 2>&1 >out.log` and drop the log file here?

**Comment by maxicarlos08** [comment]
There you go: [out.log](https://github.com/maxicarlos08/gphoto2-rs/files/9668984/out.log)

**Comment by RReverser** [comment]
Hm, so it does look for libraries in the right directories (that was the usual problem). I wonder what else is going on.

Having `choice: "large"` actually seems more reasonable than `choice: ""`, but then both me and CI got `choice: ""` pretty consistently...

As for "Internal RAM" vs "Memory card" maybe the virtual driver really reports whatever the OS says? As in, do you by any chance develop those projects on an SD card or something?

**Comment by maxicarlos08** [comment]
> As in, do you by any chance develop those projects on an SD card or something?

No, not unless libgphoto2 confuses my NVMe with an SD card.

**Comment by RReverser** [comment]
I'm looking at the relevant code in ptp2/config.c:

```c
static struct {
	char	*name;
	char	*label;
} capturetargets[] = {
	{"sdram", N_("Internal RAM") },
	{"card", N_("Memory card") },
};

static int
_get_CaptureTarget(CONFIG_GET_ARGS) {
	unsigned int i;
	char buf[1024];

	gp_widget_new (GP_WIDGET_RADIO, _(menu->label), widget);
	gp_widget_set_name (*widget, menu->name);
	if (GP_OK != gp_setting_get("ptp2","capturetarget", buf))
		strcpy(buf,"sdram");

	for (i=0;i<sizeof (capturetargets)/sizeof (capturetargets[i]);i++) {
		gp_widget_add_choice (*widget, _(capturetargets[i].label));
		if (!strcmp (buf,capturetargets[i].name))
			gp_widget_set_value (*widget, _(capturetargets[i].label));
	}
	return GP_OK;
}
```

It seems that the choice is coming from settings file, and falls back to "sdram" ("Internal RAM") if not present. Can you check if your `~/.gphoto/settings` has `ptp2_capturetarget` property or something like that?

**Comment by maxicarlos08** [comment]
Yay found it thx: (the content of `~/.gphoto/settings`)
```
gphoto2=model=Nikon DSC D3400
gphoto2=port=usb:001,007
libgphoto=cached-images=2
ptp2=capturetarget=card
ptp2=thumbsize=large
```

**Comment by RReverser** [comment]
Was just about to say that the second one is also coming from setting `ptp2=thumbsize=large`:

```
static int
_get_Nikon_Thumbsize(CONFIG_GET_ARGS) {
	char buf[1024];

	gp_widget_new (GP_WIDGET_RADIO, _(menu->label), widget);
	gp_widget_add_choice (*widget, _("normal"));
	gp_widget_add_choice (*widget, _("large"));
	gp_widget_set_name (*widget, menu->name);
	strcpy(buf,"normal");
	gp_setting_get("ptp2","thumbsize", buf);
	gp_widget_set_value  (*widget, N_(buf));
	return GP_OK;
}
```

**Comment by RReverser** [comment]
Glad we got to the bottom of this, would hate to have flaky tests :)

**Comment by maxicarlos08** [comment]
Yep tests are now passing

**Comment by maxicarlos08** [comment]
But before I merge this, would you mind rebasing and pushing the branch with the CI for Windows and MacOS?

**Comment by RReverser** [comment]
> But before I merge this, would you mind rebasing and pushing the branch with the CI for Windows and MacOS?

I think I'll do that separately, still working on it and it's largely unrelated to this PR.

**Comment by RReverser** [comment]
(plus, it will be easier for me to check & rebase the other branch once the tests are in master)

**Pull request merged**
