### PR TITLE
Fix file info bitmasks; make all file info lazy

### PR DESCRIPTION
**Pull request by RReverser**
Like in #9, I noticed few more bitmasks - around file info - that were incorrectly bound as Rust enums in libgphoto2-sys, causing UB.

While fixing it, I also decided to make all file info expose consistent lazy interface where fields are converted & returned in individual methods instead of entire structure at once.

I've also wrapped the top-level FileInfo into a Box, since it's almost 300 bytes and can be expensive to keep & move around on stack.

### CODE REVIEW

**Comment by RReverser** [comment]
Woops, missed a few places.

**Comment by RReverser** [comment]
Fixed.

**Comment by RReverser** [comment]
Wait, I'll change one more thing.

**Comment by RReverser** [comment]
Done, decided to hide the new Box<...> inside FileInfo for slightly better ergonomics.

**Review by maxicarlos08 — APPROVED** [review]

**Pull request merged**
